#include "PdfReport.h"
#include "ReportModel.h"
#include "../../../support/io/EmitSql.h"

// Arma un PDF 1.4 paginado (fuente Courier, hasta N filas por pagina) en SQL
// puro. Devuelve una sola fila con el documento completo como text.

#define PDF_LINES_PER_PAGE 30

void emitPdfReportSelect(const DatePeriod * period) {
	char fromBuffer[11];
	char toBuffer[11];
	resolvePeriodBounds(period, fromBuffer, toBuffer);
	emitSql("WITH\n");
	emitReportHeaderCTE();
	emitSql(",\n");
	emitReportRowsCTE(fromBuffer, toBuffer, true);
	emitSql(",\n");
	emitSql("paginadas AS (\n");
	emitSql("    -- Paginacion por LINEAS (no por filas): tras el wrap multi-linea,\n");
	emitSql("    -- una operacion larga puede ocupar varias lineas y queremos que\n");
	emitSql("    -- corten parejo al cambiar de pagina.\n");
	emitSql("    SELECT texto, rn, ((rn - 1) / %d + 1)::int AS pagina\n", PDF_LINES_PER_PAGE);
	emitSql("    FROM filas_alineadas\n");
	emitSql("),\n");
	emitSql("-- Bloque PDF con el balance del periodo. Se concatena al final del\n");
	emitSql("-- bloque BT/ET de Courier de la ULTIMA pagina de datos (o de la pagina\n");
	emitSql("-- vacia si no hubo operaciones). No abre BT/ET propio: se anexa al que\n");
	emitSql("-- la tabla dejo activo, usando T* para avanzar lineas con el mismo\n");
	emitSql("-- leading. La linea '() Tj T*' inicial es una linea en blanco entre la\n");
	emitSql("-- tabla y el balance.\n");
	emitSql("balance_pdf_block AS (\n");
	emitSql("    SELECT '() Tj T*' || chr(10) ||\n");
	emitSql("           '(' || (SELECT separator_line FROM cabecera) || ') Tj T*' || chr(10) ||\n");
	emitSql("           '(Balance del periodo) Tj T*' || chr(10) ||\n");
	emitSql("           '(' || (SELECT separator_line FROM cabecera) || ') Tj T*' || chr(10) ||\n");
	emitSql("           COALESCE((SELECT string_agg(\n");
	emitSql("               '(' || rpad(divisa, %d) || ' ingresos: ' || lpad(to_char(ingresos, 'FM9999999990.00'), 15) || ') Tj T*' || chr(10) ||\n", COL_DIVISA_WIDTH);
	emitSql("               '(' || rpad(divisa, %d) || ' egresos:  ' || lpad(to_char(egresos,  'FM9999999990.00'), 15) || ') Tj T*' || chr(10) ||\n", COL_DIVISA_WIDTH);
	emitSql("               '(' || rpad(divisa, %d) || ' balance:  ' || lpad(to_char(neto,     'FM9999999990.00'), 15) || ') Tj T*',\n", COL_DIVISA_WIDTH);
	emitSql("               chr(10) ORDER BY divisa) FROM balance),\n");
	emitSql("               '(Sin movimientos en el periodo.) Tj T*') AS bal\n");
	emitSql("),\n");
	emitSql("-- Body de cada pagina de DATOS: 3 bloques BT/ET para que cada uno use\n");
	emitSql("-- su fuente y posicion independientes:\n");
	emitSql("--   1) Titulo en Helvetica-Bold 14 (/F1) en Y=565.\n");
	emitSql("--   2) Periodo en Helvetica-Bold 10 (/F1) en Y=545.\n");
	emitSql("--   3) Tabla en Courier 9 (/F2) en Y=520 con leading 11.\n");
	emitSql("-- La ULTIMA pagina ademas anexa el balance dentro del mismo BT/ET de\n");
	emitSql("-- Courier (antes del ET final).\n");
	emitSql("paginas_data AS (\n");
	emitSql("    SELECT pagina,\n");
	emitSql("           'BT /F1 14 Tf 30 565 Td (Reporte de operaciones - pagina ' || pagina::text || ') Tj ET' || chr(10) ||\n");
	emitSql("           'BT /F1 10 Tf 30 545 Td (Periodo: %s a %s) Tj ET' || chr(10) ||\n", fromBuffer, toBuffer);
	emitSql("           'BT /F2 9 Tf 30 520 Td 11 TL' || chr(10) ||\n");
	emitSql("           '(' || (SELECT header_line FROM cabecera) || ') Tj T*' || chr(10) ||\n");
	emitSql("           '(' || (SELECT separator_line FROM cabecera) || ') Tj T*' || chr(10) ||\n");
	emitSql("           string_agg('(' || texto || ') Tj T*', chr(10) ORDER BY rn) || chr(10) ||\n");
	emitSql("           CASE WHEN pagina = (SELECT MAX(pagina) FROM paginadas)\n");
	emitSql("                THEN (SELECT bal FROM balance_pdf_block) || chr(10)\n");
	emitSql("                ELSE '' END ||\n");
	emitSql("           'ET' AS s\n");
	emitSql("    FROM paginadas\n");
	emitSql("    GROUP BY pagina\n");
	emitSql("),\n");
	emitSql("-- Si no hubo operaciones generamos una unica pagina con el mensaje y el\n");
	emitSql("-- balance (que en ese caso dice 'Sin movimientos en el periodo.').\n");
	emitSql("paginas AS (\n");
	emitSql("    SELECT pagina, s FROM paginas_data\n");
	emitSql("    UNION ALL\n");
	emitSql("    SELECT 1 AS pagina,\n");
	emitSql("           'BT /F1 14 Tf 30 565 Td (Reporte de operaciones) Tj ET' || chr(10) ||\n");
	emitSql("           'BT /F1 10 Tf 30 545 Td (Periodo: %s a %s) Tj ET' || chr(10) ||\n", fromBuffer, toBuffer);
	emitSql("           'BT /F2 9 Tf 30 520 Td 11 TL' || chr(10) ||\n");
	emitSql("           '(Sin operaciones en el periodo.) Tj T*' || chr(10) ||\n");
	emitSql("           (SELECT bal FROM balance_pdf_block) || chr(10) ||\n");
	emitSql("           'ET'\n");
	emitSql("    WHERE NOT EXISTS (SELECT 1 FROM paginas_data)\n");
	emitSql("),\n");
	emitSql("meta AS (\n");
	emitSql("    -- font1_num = primera fuente (Helvetica-Bold), font2_num = segunda (Courier).\n");
	emitSql("    SELECT COUNT(*)::int AS n,\n");
	emitSql("           (3 + 2 * COUNT(*))::int AS font1_num,\n");
	emitSql("           (4 + 2 * COUNT(*))::int AS font2_num\n");
	emitSql("    FROM paginas\n");
	emitSql("),\n");
	emitSql("-- Objetos numerados; el orden en el archivo coincide con el num.\n");
	emitSql("objetos AS (\n");
	emitSql("    SELECT 1 AS num,\n");
	emitSql("           '1 0 obj' || chr(10) || '<< /Type /Catalog /Pages 2 0 R >>' || chr(10) || 'endobj' AS body\n");
	emitSql("    UNION ALL\n");
	emitSql("    SELECT 2,\n");
	emitSql("           '2 0 obj' || chr(10) ||\n");
	emitSql("           '<< /Type /Pages /Kids [' ||\n");
	emitSql("           (SELECT string_agg((2 + p)::text || ' 0 R', ' ' ORDER BY p)\n");
	emitSql("            FROM generate_series(1, (SELECT n FROM meta)) AS gs(p)) ||\n");
	emitSql("           '] /Count ' || (SELECT n FROM meta)::text || ' >>' || chr(10) || 'endobj'\n");
	emitSql("    UNION ALL\n");
	emitSql("    SELECT (2 + gs.p)::int,\n");
	emitSql("           (2 + gs.p)::text || ' 0 obj' || chr(10) ||\n");
	emitSql("           '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] ' ||\n");
	emitSql("           '/Resources << /Font << /F1 ' || (SELECT font1_num FROM meta)::text || ' 0 R ' ||\n");
	emitSql("           '/F2 ' || (SELECT font2_num FROM meta)::text || ' 0 R >> >> ' ||\n");
	emitSql("           '/Contents ' || (2 + (SELECT n FROM meta) + gs.p)::text || ' 0 R >>' ||\n");
	emitSql("           chr(10) || 'endobj'\n");
	emitSql("    FROM generate_series(1, (SELECT n FROM meta)) AS gs(p)\n");
	emitSql("    UNION ALL\n");
	emitSql("    SELECT (2 + (SELECT n FROM meta) + p.pagina)::int,\n");
	emitSql("           (2 + (SELECT n FROM meta) + p.pagina)::text || ' 0 obj' || chr(10) ||\n");
	emitSql("           '<< /Length ' || octet_length(p.s)::text || ' >>' || chr(10) ||\n");
	emitSql("           'stream' || chr(10) || p.s || chr(10) || 'endstream' || chr(10) || 'endobj'\n");
	emitSql("    FROM paginas p\n");
	emitSql("    UNION ALL\n");
	emitSql("    SELECT (SELECT font1_num FROM meta),\n");
	emitSql("           (SELECT font1_num FROM meta)::text || ' 0 obj' || chr(10) ||\n");
	emitSql("           '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>' || chr(10) || 'endobj'\n");
	emitSql("    UNION ALL\n");
	emitSql("    SELECT (SELECT font2_num FROM meta),\n");
	emitSql("           (SELECT font2_num FROM meta)::text || ' 0 obj' || chr(10) ||\n");
	emitSql("           '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>' || chr(10) || 'endobj'\n");
	emitSql("),\n");
	emitSql("-- Offset acumulado de cada objeto en el archivo: 9 (header + LF) +\n");
	emitSql("-- octet_length() de los previos, contando un LF entre cada uno.\n");
	emitSql("con_offset AS (\n");
	emitSql("    SELECT num, body,\n");
	emitSql("           9 + COALESCE(SUM(octet_length(body) + 1) OVER (\n");
	emitSql("               ORDER BY num ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING\n");
	emitSql("           ), 0) AS off\n");
	emitSql("    FROM objetos\n");
	emitSql("),\n");
	emitSql("totales AS (\n");
	emitSql("    SELECT 9 + COALESCE(SUM(octet_length(body) + 1), 0) AS xref_off,\n");
	emitSql("           COUNT(*)::int + 1 AS size\n");
	emitSql("    FROM objetos\n");
	emitSql(")\n");
	emitSql("SELECT '%%PDF-1.4' || chr(10) ||\n");
	emitSql("       (SELECT string_agg(body, chr(10) ORDER BY num) FROM con_offset) || chr(10) ||\n");
	emitSql("       'xref' || chr(10) ||\n");
	emitSql("       '0 ' || (SELECT size FROM totales)::text || chr(10) ||\n");
	emitSql("       '0000000000 65535 f ' || chr(10) ||\n");
	emitSql("       (SELECT string_agg(to_char(off, 'FM0000000000') || ' 00000 n ', chr(10) ORDER BY num)\n");
	emitSql("        FROM con_offset) || chr(10) ||\n");
	emitSql("       'trailer' || chr(10) ||\n");
	emitSql("       '<< /Size ' || (SELECT size FROM totales)::text || ' /Root 1 0 R >>' || chr(10) ||\n");
	emitSql("       'startxref' || chr(10) ||\n");
	emitSql("       (SELECT xref_off FROM totales)::text || chr(10) ||\n");
	emitSql("       '%%%%EOF' AS reporte_pdf");
}
